"""create costumer table

Revision ID: 1e20fe2d081f
Revises: 
Create Date: 2021-05-30 22:02:57.251394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e20fe2d081f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costumer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costumer_email'), 'costumer', ['email'], unique=True)
    op.create_index(op.f('ix_costumer_id'), 'costumer', ['id'], unique=False)
    op.create_index(op.f('ix_costumer_name'), 'costumer', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_costumer_name'), table_name='costumer')
    op.drop_index(op.f('ix_costumer_id'), table_name='costumer')
    op.drop_index(op.f('ix_costumer_email'), table_name='costumer')
    op.drop_table('costumer')
    # ### end Alembic commands ###
