"""empty message

Revision ID: money to numeric
Revises: first
Create Date: 2021-06-06 00:58:04.246535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'money to numeric'
down_revision = 'first'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=postgresql.MONEY(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=postgresql.MONEY(),
               existing_nullable=False)
    # ### end Alembic commands ###
