const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 5.0,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id: '2',
            name: 'Adidas Slim Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 100,
            countInStock: 15,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 9,
            description: 'High quality product',
        },
        {
            _id: '3',
            name: 'Lacoste Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 80,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 4.0,
            numReviews: 8,
            description: 'High quality product',
        },
        {
            _id: '4',
            name: 'Nike Slim Pants',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 120,
            countInStock: 5,
            brand: 'Nike',
            rating: 3.8,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id: '5',
            name: 'Adidas Slim Pants',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 120,
            countInStock: 5,
            brand: 'Adidas',
            rating: 3.3,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id: '6',
            name: 'Lacoste Slim Pants',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 120,
            countInStock: 12,
            brand: 'Lacoste',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        },
    ]
}

export default data
